import React, { useState } from 'react';
import { FileUploader } from '../ui/FileUploader';
import { MdCloudUpload, MdDownload, MdRefresh, MdAutorenew } from 'react-icons/md';
import { useFileManager } from '../../hooks/useFileManager';
import { RatingPrompt } from '../ui/RatingPrompt';

interface MockApiToolProps {
  title: string;
  accept: string;
  outputExtension: string;
  toolName: string;
  seoContent?: React.ReactNode;
}

export const MockApiTool: React.FC<MockApiToolProps> = ({ title, accept, outputExtension, toolName, seoContent }) => {
  const [file, setFile] = useState<File | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [outputUrl, setOutputUrl] = useState<string | null>(null);
  const { saveFile } = useFileManager();

  const handleFiles = (files: File[]) => {
    if (files.length > 0) {
      setFile(files[0]);
      setOutputUrl(null);
    }
  };

  const processFile = () => {
    if (!file) return;
    setIsProcessing(true);
    
    setTimeout(() => {
      const content = `Mock output for ${file.name}\nConverted to ${outputExtension.toUpperCase()}.\n\nIn a real app, this would be a proper ${outputExtension} file generated by a backend API.`;
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      setOutputUrl(url);
      setIsProcessing(false);

      const mimeType = outputExtension === 'pdf' ? 'application/pdf' :
                       outputExtension === 'doc' ? 'application/msword' : 'text/plain';
                       
      saveFile({
        name: `FileMint_Converted_${file.name.split('.')[0]}.${outputExtension}`,
        toolName: toolName,
        type: mimeType,
        size: blob?.size || 0
      }, blob);
    }, 1500);
  };

  return (
    <div className="flex flex-col gap-6 w-full animate-in fade-in duration-300">
      
      {outputUrl ? (
        <div className="flex flex-col items-center py-6 animate-in zoom-in-95 duration-300 text-center">
          <div className="w-[64px] h-[64px] rounded-full bg-green-500/10 text-green-500 flex items-center justify-center mb-4">
            <MdDownload size={32} />
          </div>
          <h3 className="text-[18px] font-bold text-[#111827] dark:text-gray-100 mb-1 font-display tracking-tight">Conversion Successful!</h3>
          <p className="text-[13px] text-[#6B7280] dark:text-gray-400 mb-8 font-medium">Your {outputExtension.toUpperCase()} file is ready.</p>

          <div className="flex flex-col gap-3 w-full">
            <a
              href={outputUrl}
              download={`FileMint_Converted_${file?.name.split('.')[0]}.${outputExtension}`}
              className="w-full h-[48px] bg-brand-pink text-white rounded-[12px] font-bold flex items-center justify-center gap-2 shadow-lg shadow-brand-pink/20 active:scale-95 transition-all"
            >
              <MdDownload size={20} /> Download File
            </a>
            <button 
              onClick={() => { setFile(null); setOutputUrl(null); }}
              className="w-full h-[48px] bg-brand-light text-brand-pink rounded-[12px] font-bold active:scale-95 transition-all text-[14px]"
            >
              Convert Another
            </button>
          </div>
          {RatingPrompt && <div className="w-full mt-8"><RatingPrompt /></div>}
        </div>
      ) : (
        <div className="flex flex-col gap-6">
          {!file ? (
            <FileUploader 
              accept={accept} 
              multiple={false} 
              onFilesSelected={handleFiles} 
              label="Select file to process"
              subLabel={`Tap to upload for ${title}`}
            />
          ) : (
            <div className="flex flex-col gap-6 animate-in slide-in-from-bottom-2 duration-300">
              <div className="flex items-center gap-3 p-3.5 bg-[#F8F9FC] dark:bg-slate-900/50 rounded-[12px] border border-[#E5E7EB] dark:border-slate-800">
                <div className="w-[44px] h-[44px] bg-brand-light text-brand-pink rounded-[10px] flex items-center justify-center flex-shrink-0">
                  <MdCloudUpload size={24} />
                </div>
                <div className="min-w-0 flex-1">
                  <p className="text-[14px] font-bold text-[#111827] dark:text-white truncate">{file.name}</p>
                  <p className="text-[12px] font-medium text-[#6B7280]">{(file.size / 1024 / 1024).toFixed(2)} MB</p>
                </div>
                <button onClick={() => setFile(null)} className="text-[12px] font-bold text-brand-pink hover:bg-brand-light px-3 py-1.5 rounded-lg transition-all">Replace</button>
              </div>

              <div className="px-1">
                 <p className="text-[14px] font-bold text-[#111827] dark:text-gray-200 mb-2">Output Format</p>
                 <div className="h-[48px] flex items-center px-4 bg-[#F8F9FC] dark:bg-slate-900 border border-[#E5E7EB] dark:border-slate-800 rounded-[12px] text-[15px] font-bold text-[#111827]">
                    {outputExtension.toUpperCase()}
                 </div>
              </div>
              
              <button 
                onClick={processFile}
                disabled={isProcessing}
                className="w-full h-[52px] bg-brand-pink text-white rounded-[12px] font-bold text-[15px] shadow-lg shadow-brand-pink/20 active:scale-[0.98] transition-all flex justify-center items-center gap-2 mt-2"
              >
                {isProcessing ? <><MdAutorenew className="animate-spin" size={20} /> Converting file...</> : `Convert to ${outputExtension.toUpperCase()}`}
              </button>
            </div>
          )}
        </div>
      )}

      {/* SEO ARTICLE */}
      {seoContent && (
        <div className="mt-4 pt-6 border-t border-gray-50 dark:border-slate-700/50">
          {seoContent}
        </div>
      )}
    </div>
  );
};
